# Generated by Django 3.2.4 on 2021-09-06 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('questionnaires', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question_type', models.CharField(
                    choices=[('1', '选择'), ('2', '填空'), ('3', '矩阵'), ('4', '简答'), ('5', '表格'), ('6', '附件')], default='1',
                    max_length=1, verbose_name='问题类型')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('stem', models.TextField(verbose_name='题干')),
                ('is_required', models.BooleanField(verbose_name='必答')),
                ('min_score', models.DecimalField(decimal_places=6, max_digits=19, verbose_name='最低分数')),
                ('max_score', models.DecimalField(decimal_places=6, max_digits=19, verbose_name='最高分数')),
                ('rubric', models.CharField(choices=[('A', '自动打分'), ('E', '专家打分')], default='E', max_length=1,
                                            verbose_name='打分方式')),
                ('rubric_detail', models.TextField(blank=True, null=True, verbose_name='打分细则')),
                ('qnaire',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaires.questionnaire',
                                   verbose_name='所属问卷ID')),
            ],
            options={
                'db_table': 'app_question',
                'managed': True,
            },
        ),
    ]
