# Generated by Django 3.2.4 on 2021-11-15 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='order',
            field=models.IntegerField(default=0, verbose_name='序号'),
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('id', 'order')},
        ),
    ]
