# Generated by Django 3.2.4 on 2021-11-15 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_alter_question_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('stem', 'order', 'question_type')},
        ),
    ]
