# Generated by Django 3.2.4 on 2021-09-06 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='机构名称')),
                ('org_type',
                 models.CharField(choices=[('I', '研究所'), ('B', '分院'), ('S', '支撑单位'), ('U', '学校')], default='I',
                                  max_length=1, verbose_name='机构类别')),
                ('is_active', models.BooleanField(default=True, verbose_name='有效')),
                ('address', models.CharField(max_length=100, null=True, verbose_name='地址')),
                ('postcode', models.CharField(max_length=6, null=True, verbose_name='邮编')),
                ('department', models.CharField(max_length=255, null=True, verbose_name='部门')),
                ('phone', models.CharField(max_length=15, null=True, verbose_name='电话号码')),
                ('parent_org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT,
                                                 to='organizations.organization', verbose_name='上级机构')),
            ],
            options={
                'db_table': 'app_organization',
                'managed': True,
            },
        ),
    ]
