# Generated by Django 3.2.4 on 2021-09-06 14:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='名称')),
                ('status',
                 models.CharField(choices=[('1', '未开始'), ('2', '进行中'), ('3', '已结束')], default='1', max_length=1,
                                  verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'app_progress',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='名称')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('send_with', models.CharField(choices=[('A', '匿名邮件'), ('L', '登录系统')], default='L', max_length=1,
                                               verbose_name='发放方式')),
                ('will_mark', models.BooleanField(default=True, verbose_name='是否计分')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='结束时间')),
            ],
            options={
                'db_table': 'app_project',
                'managed': True,
            },
        ),
    ]
