# Generated by Django 3.2.4 on 2021-09-06 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('junctions', '0002_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL,
                                    verbose_name='管理员ID'),
        ),
        migrations.AddField(
            model_name='project',
            name='org',
            field=models.ManyToManyField(related_name='project', through='junctions.ProjectOrganization',
                                         to='organizations.Organization', verbose_name='参评机构'),
        ),
        migrations.AddField(
            model_name='progress',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL,
                                    verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='progress',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project',
                                    verbose_name='所属项目ID'),
        ),
    ]
