# Generated by Django 3.2.4 on 2021-09-06 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('organizations', '0001_initial'),
        ('junctions', '0001_initial'),
        ('questions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='questionexpert',
            name='expert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL,
                                    verbose_name='专家ID'),
        ),
        migrations.AddField(
            model_name='questionexpert',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.question',
                                    verbose_name='问题ID'),
        ),
        migrations.AddField(
            model_name='projectorganization',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='project_membership',
                                    to='organizations.organization', verbose_name='机构ID'),
        ),
        migrations.AddField(
            model_name='projectorganization',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='project_membership',
                                    to='projects.project', verbose_name='评估项目ID'),
        ),
        migrations.AlterUniqueTogether(
            name='questionexpert',
            unique_together={('question', 'expert')},
        ),
        migrations.AlterUniqueTogether(
            name='projectorganization',
            unique_together={('project', 'org')},
        ),
    ]
