# Generated by Django 3.2.4 on 2021-09-06 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('description', models.TextField(verbose_name='描述')),
                ('identifier', models.CharField(max_length=50, verbose_name='标识符')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project',
                                              verbose_name='所属项目ID')),
            ],
            options={
                'db_table': 'app_questionnaire',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='名称')),
                ('weight', models.IntegerField(verbose_name='权重')),
                ('parent_indicator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                                       to='questionnaires.indicator', verbose_name='上级指标')),
                ('qnaire',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaires.questionnaire',
                                   verbose_name='所属问卷ID')),
            ],
            options={
                'db_table': 'app_indicator',
                'managed': True,
            },
        ),
    ]
