# Generated by Django 3.2.4 on 2021-09-06 14:43

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(blank=True, null=True, verbose_name='答案')),
                ('attachment', models.TextField(blank=True, null=True, verbose_name='附件')),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='上次更新时间')),
                ('final_score', models.DecimalField(decimal_places=6, max_digits=19, null=True, verbose_name='最终分数')),
            ],
            options={
                'db_table': 'app_submission',
                'managed': True,
            },
        ),
    ]
